stages:
  - test
  - deploy

unit_tests:
  stage: test
  tags:
    - shared
  script:
    - pip install -r requirements.txt
    - python -m pytest tests/ -v

deploy_to_production:
  stage: deploy
  tags:
    - shared
  script:
    - echo "Deployment simulation started"
    - echo "Deployment completed"