stages:
  - test
  - deploy

unit_tests:
  stage: test
  tags:
    - shared
  before_script:
    - python --version
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - python -m pytest tests/ -v

deploy_to_production:
  stage: deploy
  tags:
    - shared
  script:
    - echo "Starting deployment process..."
    - echo "Copying files to production server..."
    - echo "Running deployment simulation..."
    - echo "Application deployed successfully!"
    - echo "Deployment completed at: 2025"